### ISSUE TITLE
How to get RAW8 / Bayer8 

### ISSUE THREAD

**Issue by carlesgutierrez** [katotetsuro/ofxFlyCapture#1]
Hello, 
 I've tried this addon and it's working for Mono and RGB8 formats. Simple and working. Great!
 But that formats for the BFLY-PGE-31S4C-C camera is slow ( about 8 fps ). 
 I need to use the RAW8, that will give the 35 FPS. 

 How can I do this here? I've tried to change it by my own but I could set that pixel format working.

**Comment by katotetsuro** [comment]
Hi, @carlesgutierrez 
Thank you for your kind report!
I also read e-mail from you. Is this issue solved by other's folk?
If it's solved, please ignore below comments 🙇 

I think if you want to use RAW8 / Bayer8, handle format around here
https://github.com/katotetsuro/ofxFlyCapture/blob/master/src/ofxFlyCapture.cpp#L106-L130
and convert to RGB before this line (if you need ofImage)
https://github.com/katotetsuro/ofxFlyCapture/blob/master/src/ofxFlyCapture.cpp#L206

To convert pixel format, there is a API in FlyCapture SDK
`virtual Error Convert ( PixelFormat format, Image ∗ pDestImage ) const`
I don't have an experience of this API, so I'm sorry if it is wrong.

I looked thomasvanta's folk, and I find big difference from mine is separating frame retrieving thread.
In my implementation, fps of App is bounded by camera capture fps.

**Comment by carlesgutierrez** [comment]
Thanks for your reply @katotetsuro 
You are so kind. It's solved but good to have a double check why is this happening. 

So internal pixel format conversions were already happening. And It depends on the camera configuration. Is possible to configure them previously and fetch them like that. PixelFormat conversions runs for all formats pretty quick. Some formats will be quick converted than others but as far I've seen it's ok for all them. 

So configuring RAW8 also smaller image sizes ( mode 1,2 ) help to run it faster throught the network. But, I've to say sometimes I've got it working that fast with RGB too... That made me mad. Then I've understood that there is something else about the network and the App FPS.

 Said this, @thomasvanta thread improved to handle all the info from cameras. When the network packages are stable in terms of frequency and transfer velocity ( using Giga-Ethernet router in the middle, gave me better results than directly to my laptop ). The App remains more stable and is able to handle all. Then all sync fast! Normally It takes >4 seconds to the App until really works at the maximum Framerate, otherwise 6-8 App fps...

**Comment by katotetsuro** [comment]
Hmm, now I understand almost your situation. And I agree it may be a kind of network related problem.

These are points I care look carefully when I use GigE Cameras, 

- use gigabit ethernet switching-hub (you already mentioned)
- enable jumbo packet(MTU=9000) in switching-hub
- enable jumbo packet in Network Interface Configuration
- use Cat6 cable (in some case, cat5e is slow)
- check maximum packet size is 9000 in GigEConfigurator(part of pointgrey software)
- set packet delay and packet size in FlyCapture Viewer

Although you might already know, hope it helps you.

**Comment by carlesgutierrez** [comment]
thanks, that's a good resumed TODO list to have in mind. 

I missed GigEConfigurator, and to set the right delay config... 🌊 🌊 🏄 

But still some issues here: 

* My Ethernet Device returns --> 9202 MTU in red, does not look good... [in this manual](https://eu.ptgrey.com/support/downloads/10365) It's in green.. 

![ethernetover9000](https://user-images.githubusercontent.com/203877/44313674-f1514c80-a40c-11e8-83d1-25cacac1a478.PNG)

* Now that I'm using a new switch ([ plug and play POE+switch](https://www.broadbandbuyer.com/products/30729-netgear-gs108pp-100eus/specifications/) ) that allow Jumbo ( says up to 9216 bytes ) If I use 9000 in FlyCapture config, it freezes. Weird right? But If I set a bit less it works.

* Still I've that mad behavior, hard to explain.  I can get camera working properly almost for all pixelformat and size image configuration, but I've to wait or stress with my computer for a short while , then the App reach the desired right FPS.  Once that FPS works ok for ever. That happened in 098, 010, with you addon or @thomasvanta. I've watched that once just playing with a simple video player.
 In my opinion there are some threads working hard over there ( for camera and some times for the video ) that are not allowing OF to get fast enough for process each frame.  Any tips here?

**Comment by carlesgutierrez** [comment]
@katotetsuro  I Can confirm that mad behavior is not anymore using other Ethernet Devices with 9000 MTU ( green ). To do it I've tried another computer with a regular GigEthernet card. For future tests, I will try some [USB GigE devices](https://eu.dlink.com/uk/en/products/dub-1312-usb-3-gigabit-ethernet-adapter), just to see If I can handle it properly in my laptop.

**Comment by katotetsuro** [comment]
I am glad that the problem was solved!
In my experience, Intel's NIC is stable.
Some USB-GigE adapter doesn't have jumbo frame property, so you might be care.
Anyway, good luck to you.
